export const cars = [
  {
    title: "Chevrolet Camaro",
    type: "Sedan",
    rentPrice: 63.29,
    capacity: 2,
    transmission: "Manual",
    location: "Munich",
    fuelCapacity: 41,
    description:
      "This car combines excellent performance with a comfortable interior and advanced technology.  Ideal for both city driving and long-distance travel, it offers a smooth ride, ample space, and efficient fuel consumption. Safety features include ABS, airbags, and a robust security system. The vehicle's entertainment system provides a great audio experience, making every journey enjoyable. Perfect for families, individuals, or business trips, it's a top choice for anyone seeking a reliable and stylish car.",
    images: ["/images/suv-dark.png"],
    blurDataURL: ["/images/suv-dark.png"],
    ownerId: "user-025",
  },
  {
    title: "Volkswagen Golf",
    type: "Sedan",
    rentPrice: 89.6,
    capacity: 4,
    transmission: "Automatic",
    location: "London",
    fuelCapacity: 62,
    description:
      "This electric car represents the future of driving, with zero emissions and cutting-edge technology. Its impressive battery range and fast-charging capabilities make it a practical choice for daily use. The quiet, smooth ride is complemented by a minimalist yet comfortable interior, featuring advanced driver-assistance systems for a safer driving experience.",
    images: ["/images/suv-dark.png"],
    blurDataURL: ["/images/suv-dark.png"],
    ownerId: "user-026",
  },
  {
    title: "Honda Civic",
    type: "Hybrid",
    rentPrice: 141.1,
    capacity: 8,
    transmission: "Automatic",
    location: "Moscow",
    fuelCapacity: 63,
    description:
      "This sports car delivers an adrenaline-pumping driving experience with its high-performance engine and aerodynamic design. The cockpit is designed for the driver, with intuitive controls and a focus on ergonomics. It's a perfect match for those who crave speed and precision, offering an exhilarating ride without compromising on safety and reliability.",
    images: ["/images/suv-dark.png"],
    blurDataURL: ["/images/suv-dark.png"],
    ownerId: "user-027",
  },
  {
    title: "Toyota Corolla",
    type: "Coupe",
    rentPrice: 118.65,
    capacity: 8,
    transmission: "Automatic",
    location: "Paris",
    fuelCapacity: 51,
    description:
      "This sports car delivers an adrenaline-pumping driving experience with its high-performance engine and aerodynamic design. The cockpit is designed for the driver, with intuitive controls and a focus on ergonomics. It's a perfect match for those who crave speed and precision, offering an exhilarating ride without compromising on safety and reliability.",
    images: ["/images/suv-dark.png"],
    blurDataURL: ["/images/suv-dark.png"],
    ownerId: "user-028",
  },
  {
    title: "Honda Civic",
    type: "Hybrid",
    rentPrice: 132.7,
    capacity: 2,
    transmission: "Automatic",
    location: "Cape Town",
    fuelCapacity: 42,
    description:
      "This car combines excellent performance with a comfortable interior and advanced technology.  Ideal for both city driving and long-distance travel, it offers a smooth ride, ample space, and efficient fuel consumption. Safety features include ABS, airbags, and a robust security system. The vehicle's entertainment system provides a great audio experience, making every journey enjoyable. Perfect for families, individuals, or business trips, it's a top choice for anyone seeking a reliable and stylish car.",
    images: ["/images/suv-dark.png"],
    blurDataURL: ["/images/suv-dark.png"],
    ownerId: "user-029",
  },
  {
    title: "Toyota Corolla",
    type: "Hatchback",
    rentPrice: 84.89,
    capacity: 2,
    transmission: "Automatic",
    location: "Dubai",
    fuelCapacity: 54,
    description:
      "This classic car combines timeless design with modern technology. Restored to its original glory, it features a vintage exterior with a fully updated interior, including contemporary safety and entertainment systems. A joy to drive, it appeals to collectors and enthusiasts alike, offering a unique blend of history and modernity.",
    images: ["/images/suv-dark.png"],
    blurDataURL: ["/images/suv-dark.png"],
    ownerId: "user-030",
  },
  {
    title: "Ford Mustang",
    type: "Hybrid",
    rentPrice: 144.36,
    capacity: 5,
    transmission: "Automatic",
    location: "Tokyo",
    fuelCapacity: 47,
    description:
      "This SUV is built for adventure, with a robust exterior and a spacious, durable interior. It's equipped with 4-wheel drive and advanced off-road capabilities, making it perfect for exploring the great outdoors. Inside, you'll find a comfortable cabin with plenty of room for passengers and cargo, along with safety features that give you confidence on any terrain.",
    images: ["/images/suv-dark.png"],
    blurDataURL: ["/images/suv-dark.png"],
    ownerId: "user-031",
  },
  {
    title: "Peugeot 208",
    type: "Sports",
    rentPrice: 84.9,
    capacity: 8,
    transmission: "Manual",
    location: "Beijing",
    fuelCapacity: 50,
    description:
      "This sports car delivers an adrenaline-pumping driving experience with its high-performance engine and aerodynamic design. The cockpit is designed for the driver, with intuitive controls and a focus on ergonomics. It's a perfect match for those who crave speed and precision, offering an exhilarating ride without compromising on safety and reliability.",
    images: ["/images/suv-dark.png"],
    blurDataURL: ["/images/suv-dark.png"],
    ownerId: "user-032",
  },
  {
    title: "Porsche 911",
    type: "Sedan",
    rentPrice: 131.23,
    capacity: 4,
    transmission: "Automatic",
    location: "New York",
    fuelCapacity: 50,
    description:
      "This electric car represents the future of driving, with zero emissions and cutting-edge technology. Its impressive battery range and fast-charging capabilities make it a practical choice for daily use. The quiet, smooth ride is complemented by a minimalist yet comfortable interior, featuring advanced driver-assistance systems for a safer driving experience.",
    images: ["/images/suv-dark.png"],
    blurDataURL: ["/images/suv-dark.png"],
    ownerId: "user-033",
  },
  {
    title: "BMW 3 Series",
    type: "Hatchback",
    rentPrice: 67.38,
    capacity: 8,
    transmission: "Automatic",
    location: "Dubai",
    fuelCapacity: 48,
    description:
      "This sports car delivers an adrenaline-pumping driving experience with its high-performance engine and aerodynamic design. The cockpit is designed for the driver, with intuitive controls and a focus on ergonomics. It's a perfect match for those who crave speed and precision, offering an exhilarating ride without compromising on safety and reliability.",
    images: ["/images/suv-dark.png"],
    blurDataURL: ["/images/suv-dark.png"],
    ownerId: "user-034",
  },
  {
    title: "Chevrolet Camaro",
    type: "SUV",
    rentPrice: 65.62,
    capacity: 2,
    transmission: "Automatic",
    location: "Cape Town",
    fuelCapacity: 52,
    description:
      "This compact car is perfect for urban environments, offering agility and easy parking. Despite its size, the interior is surprisingly spacious, providing a comfortable ride. It comes with essential safety features and a fuel-efficient engine, making it a cost-effective option. The car's modern infotainment system keeps you connected on the go, making it a great choice for city dwellers.",
    images: ["/images/suv-dark.png"],
    blurDataURL: ["/images/suv-dark.png"],
    ownerId: "user-035",
  },
  {
    title: "Nissan Altima",
    type: "Hybrid",
    rentPrice: 144.69,
    capacity: 2,
    transmission: "Automatic",
    location: "Paris",
    fuelCapacity: 65,
    description:
      "A symbol of sophistication, this car features an elegant design and a powerful yet smooth drive. The luxurious interior is crafted with attention to detail, offering maximum comfort. It's equipped with an array of safety features and a state-of-the-art navigation system. Ideal for those who value style and comfort, this car is a perfect blend of tradition and innovation.",
    images: ["/images/suv-dark.png"],
    blurDataURL: ["/images/suv-dark.png"],
    ownerId: "user-036",
  },
  {
    title: "Peugeot 208",
    type: "Hybrid",
    rentPrice: 99.79,
    capacity: 5,
    transmission: "Manual",
    location: "Tokyo",
    fuelCapacity: 52,
    description:
      "Blending luxury with performance, this car offers a refined driving experience. Its high-quality interior, equipped with the latest technology, ensures a comfortable ride. Efficient in urban settings and capable on longer journeys, it boasts outstanding fuel economy and advanced safety systems including collision detection and lane assist. The premium sound system enhances every trip, making it ideal for business or leisure travel.",
    images: ["/images/suv-dark.png"],
    blurDataURL: ["/images/suv-dark.png"],
    ownerId: "user-037",
  },
  {
    title: "Volkswagen Golf",
    type: "SUV",
    rentPrice: 116.34,
    capacity: 2,
    transmission: "Automatic",
    location: "Rome",
    fuelCapacity: 44,
    description:
      "Blending luxury with performance, this car offers a refined driving experience. Its high-quality interior, equipped with the latest technology, ensures a comfortable ride. Efficient in urban settings and capable on longer journeys, it boasts outstanding fuel economy and advanced safety systems including collision detection and lane assist. The premium sound system enhances every trip, making it ideal for business or leisure travel.",
    images: ["/images/suv-dark.png"],
    blurDataURL: ["/images/suv-dark.png"],
    ownerId: "user-037",
  },
];
