export const elements = {
  userButtonPopoverCard: "dark:bg-gray-850",
  userPreviewMainIdentifier: "dark:text-white-200",
  userPreviewSecondaryIdentifier: "dark:text-white-200",
  userButtonPopoverActionButtonIcon: "dark:text-white-200",
  userButtonPopoverActionButtonText: "dark:text-white-200",
  userButtonPopoverFooter: "hidden",
  formButtonPrimary: "bg-secondary hover:bg-primary",
  card: "dark:bg-gray-850",
  formFieldLabel: "dark:text-white-200",
  headerTitle: "dark:text-white-200 text-secondary",
  headerSubtitle: "dark:text-white-200 text-secondary opacity-70",
  dividerLine: "bg-secondary dark:opacity-50",
  dividerText: "dark:text-white-200",
  socialButtonsIconButton: "dark:bg-gray-850 hover:dark:bg-secondary border-secondary dark:border-gray-800 hover:bg-opacity-10",
  footer: "flex justify-center items-center dark:bg-gray-850",
  footerActionText: "dark:text-white-200 my-auto",
  footerActionLink: "text-secondary hover:text-primary no-underline hover:no-underline paragraph-medium",
  navbarButtonIcon: "dark:text-white-200",
  navbarButtonLabel: "dark:text-white-200",
  navbarButton: "dark:text-white-200",
  profileSectionTitleText: "dark:text-white-200",
  profileSectionPrimaryButton: "dark:bg-gray-800 dark:text-white-200",
  accordionTriggerButton: "dark:bg-gray-850 dark:text-white-200 ",
  breadcrumbsItem: "dark:text-white-200",
  modalCloseButton: "dark:text-white-200",
};
